# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd66735ad2c5781dcce44051f865e6299797f3ec74374bd7e574a396ce290a72f420a92491424a680eb61d6abf9bf80e81875babe080bc03fdb927c3c6e0ac8a

test:
  secret_key_base: 91f14f54fd4f8fb5bd835773c5bf8a32c4036e063c03b4f55305eb04bc61e04deb6a000a2057d93a5a1470cc6bcd99f0ab776a8b2c6c4f875edbe01b22e7c826

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
